const $=id=>document.getElementById(id);
const USERS_KEY="elit_pet_users_v6", SESSION_KEY="elit_pet_session_v6", DATA_PREFIX="elit_pet_data_v6_";
let state={user:null,data:null};

const emptyData=()=>({profile:{businessName:"ELIT PET GROOMING",ownerName:"",phone:"",address:"",description:""},pets:[],clients:[],appointments:[],payments:[]});
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
const money=n=>new Intl.NumberFormat("es-EC",{style:"currency",currency:"USD"}).format(Number(n)||0);
const save=()=>localStorage.setItem(DATA_PREFIX+state.user.id,JSON.stringify(state.data));
const users=()=>JSON.parse(localStorage.getItem(USERS_KEY)||"[]");
const setUsers=x=>localStorage.setItem(USERS_KEY,JSON.stringify(x));
function toast(m){$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2200)}
function loadSession(){const id=localStorage.getItem(SESSION_KEY);if(!id)return;const u=users().find(x=>x.id===id);if(u){state.user=u;state.data=JSON.parse(localStorage.getItem(DATA_PREFIX+u.id)||"null")||emptyData();showApp()}}
function showApp(){$("authView").classList.add("hidden");$("appView").classList.remove("hidden");renderAll()}
function logout(){localStorage.removeItem(SESSION_KEY);state={user:null,data:null};$("appView").classList.add("hidden");$("authView").classList.remove("hidden")}
function switchAuth(mode){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.auth===mode));$("loginForm").classList.toggle("hidden",mode!=="login");$("registerForm").classList.toggle("hidden",mode!=="register")}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>switchAuth(b.dataset.auth));
$("loginForm").onsubmit=e=>{e.preventDefault();const u=users().find(x=>x.email.toLowerCase()===$("loginEmail").value.trim().toLowerCase()&&x.password===$("loginPassword").value);if(!u)return toast("Correo o contraseña incorrectos");state.user=u;state.data=JSON.parse(localStorage.getItem(DATA_PREFIX+u.id)||"null")||emptyData();localStorage.setItem(SESSION_KEY,u.id);showApp()};
$("registerForm").onsubmit=e=>{e.preventDefault();const email=$("regEmail").value.trim().toLowerCase();if(users().some(u=>u.email===email))return toast("Ese correo ya está registrado");const u={id:uid(),email,password:$("regPassword").value};const d=emptyData();d.profile.businessName=$("regBusiness").value.trim();d.profile.ownerName=$("regOwner").value.trim();const us=users();us.push(u);setUsers(us);localStorage.setItem(DATA_PREFIX+u.id,JSON.stringify(d));localStorage.setItem(SESSION_KEY,u.id);state={user:u,data:d};showApp()};
$("logoutBtn").onclick=logout;
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>goPage(b.dataset.page));
document.querySelectorAll("[data-page-link]").forEach(b=>b.onclick=()=>goPage(b.dataset.pageLink));
function goPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===id));window.scrollTo({top:0,behavior:"smooth"})}

function renderAll(){const p=state.data.profile; $("businessLabel").textContent=p.businessName; $("ownerLabel").textContent=p.ownerName||"profesional";$("statPets").textContent=state.data.pets.length;$("statClients").textContent=state.data.clients.length;
const future=state.data.appointments.filter(a=>new Date(a.date)>=new Date()).sort((a,b)=>new Date(a.date)-new Date(b.date));$("statAppointments").textContent=future.length;
const total=state.data.payments.reduce((s,p)=>s+Number(p.amount||0),0);$("statRevenue").textContent=money(total);
$("financeTotal").textContent=money(total);const now=new Date();$("financeMonth").textContent=money(state.data.payments.filter(p=>{const d=new Date(p.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,p)=>s+Number(p.amount||0),0));
renderUpcoming(future);renderPets();renderClients();renderAppointments();renderPayments();fillProfile()}
function renderUpcoming(list){$("upcomingList").innerHTML=list.slice(0,5).map(a=>{const pet=state.data.pets.find(p=>p.id===a.petId);return `<div class="list-item"><div><b>${esc(pet?.name||"Mascota")}</b><div class="meta">${new Date(a.date).toLocaleString("es-EC",{dateStyle:"short",timeStyle:"short"})}</div></div><span>${money(a.price)}</span></div>`}).join("")||'<div class="muted">No hay citas próximas.</div>'}
function renderPets(){const q=($("petSearch").value||"").toLowerCase();const arr=state.data.pets.filter(p=>[p.name,p.owner,p.breed].join(" ").toLowerCase().includes(q));$("petsGrid").innerHTML=arr.map(p=>`<article class="pet-card"><h3>🐾 ${esc(p.name)}</h3><div class="meta">Dueño: ${esc(p.owner)}<br>${esc(p.species)} · ${esc(p.breed||"Sin raza")}<br>${esc(p.sex)} · ${esc(p.age||"Edad no registrada")} · ${p.weight?esc(p.weight)+" kg":"Peso no registrado"}<br>Servicio: ${esc(p.service||"—")} · ${money((Number(p.price)||0)-(Number(p.discount)||0))}</div><div class="card-actions"><button class="btn ghost" onclick="editPet('${p.id}')">Editar</button><button class="btn ghost" onclick="whatsapp('${p.id}')">WhatsApp</button><button class="btn danger" onclick="deletePet('${p.id}')">Eliminar</button></div></article>`).join("")||'<div class="panel">No hay mascotas registradas todavía.</div>'}
function renderClients(){$("clientsGrid").innerHTML=state.data.clients.map(c=>{const n=state.data.pets.filter(p=>p.clientId===c.id||p.owner===c.name).length;return `<article class="client-card"><h3>👤 ${esc(c.name)}</h3><div class="meta">📞 ${esc(c.phone||"Sin teléfono")}<br>✉️ ${esc(c.email||"Sin correo")}<br>🐾 ${n} mascota(s)</div><div class="card-actions">${c.phone?`<button class="btn ghost" onclick="openWhatsAppNumber('${esc(c.phone)}','Hola ${esc(c.name)}, te escribimos de ELIT PET GROOMING 🐾')">WhatsApp</button>`:""}<button class="btn danger" onclick="deleteClient('${c.id}')">Eliminar</button></div></article>`}).join("")||'<div class="panel">No hay clientes registrados.</div>'}
function renderAppointments(){$("appointmentsList").innerHTML=state.data.appointments.sort((a,b)=>new Date(a.date)-new Date(b.date)).map(a=>{const p=state.data.pets.find(x=>x.id===a.petId);return `<article class="appointment"><b>📅 ${new Date(a.date).toLocaleString("es-EC",{dateStyle:"full",timeStyle:"short"})}</b><div class="meta">🐶 ${esc(p?.name||"Mascota")} · ${esc(a.service||"Servicio")} · ${money(a.price)}<br>${esc(a.notes||"")}</div><div class="card-actions"><button class="btn danger" onclick="deleteAppointment('${a.id}')">Eliminar</button>${p?.owner?`<button class="btn ghost" onclick="whatsapp('${p.id}')">Recordar por WhatsApp</button>`:""}</div></article>`}).join("")||'<div class="panel">No hay citas.</div>'}
function renderPayments(){$("paymentsList").innerHTML=state.data.payments.sort((a,b)=>new Date(b.date)-new Date(a.date)).map(p=>{const pet=state.data.pets.find(x=>x.id===p.petId);return `<div class="list-item"><div><b>${money(p.amount)}</b><div class="meta">${esc(pet?.name||"—")} · ${esc(p.method)} · ${new Date(p.date).toLocaleDateString("es-EC")}</div></div><button class="btn danger" onclick="deletePayment('${p.id}')">Eliminar</button></div>`}).join("")||'<div class="muted">No hay pagos registrados.</div>'}
function renderRecent(){ $("recentPets").innerHTML=state.data.pets.slice(-5).reverse().map(p=>`<div class="list-item"><span>🐾 <b>${esc(p.name)}</b><br><small>${esc(p.owner)}</small></span><span>${money((Number(p.price)||0)-(Number(p.discount)||0))}</span></div>`).join("")||'<div class="muted">No hay mascotas.</div>'}
function fillProfile(){const p=state.data.profile;$("profileBusiness").value=p.businessName||"";$("profileOwner").value=p.ownerName||"";$("profilePhone").value=p.phone||"";$("profileAddress").value=p.address||"";$("profileDescription").value=p.description||"";renderRecent()}
$("profileForm").onsubmit=e=>{e.preventDefault();Object.assign(state.data.profile,{businessName:$("profileBusiness").value.trim(),ownerName:$("profileOwner").value.trim(),phone:$("profilePhone").value.trim(),address:$("profileAddress").value.trim(),description:$("profileDescription").value.trim()});save();renderAll();toast("Información guardada")};
$("petSearch").oninput=renderPets;
function openPet(p={}){ $("petDialogTitle").textContent=p.id?"Editar mascota":"Registrar mascota"; $("petId").value=p.id||"";$("petName").value=p.name||"";$("petOwner").value=p.owner||"";$("petPhone").value=p.phone||"";$("petSpecies").value=p.species||"Perro";$("petBreed").value=p.breed||"";$("petSex").value=p.sex||"No especificado";$("petAge").value=p.age||"";$("petWeight").value=p.weight||"";$("petService").value=p.service||"";$("petPrice").value=p.price||"";$("petDiscount").value=p.discount||0;$("petNext").value=p.nextVisit||"";$("petNotes").value=p.notes||"";$("petDialog").showModal()}
$("newPetBtn").onclick=$("addPetBtn").onclick=()=>openPet();
$("petForm").onsubmit=e=>{e.preventDefault();const id=$("petId").value||uid();const old=state.data.pets.find(p=>p.id===id)||{};const p={...old,id,name:$("petName").value.trim(),owner:$("petOwner").value.trim(),phone:$("petPhone").value.trim(),species:$("petSpecies").value,breed:$("petBreed").value.trim(),sex:$("petSex").value,age:$("petAge").value.trim(),weight:$("petWeight").value,service:$("petService").value.trim(),price:Number($("petPrice").value||0),discount:Number($("petDiscount").value||0),nextVisit:$("petNext").value,notes:$("petNotes").value.trim(),updatedAt:new Date().toISOString()};const client=state.data.clients.find(c=>c.name.toLowerCase()===p.owner.toLowerCase());if(client)p.clientId=client.id;if(!old.createdAt)p.createdAt=new Date().toISOString();const i=state.data.pets.findIndex(x=>x.id===id);if(i>=0)state.data.pets[i]=p;else state.data.pets.push(p);save();$("petDialog").close();renderAll();toast("Mascota guardada")};
window.editPet=id=>openPet(state.data.pets.find(p=>p.id===id)||{});
window.deletePet=id=>{if(!confirm("¿Eliminar esta mascota?"))return;state.data.pets=state.data.pets.filter(p=>p.id!==id);state.data.appointments=state.data.appointments.filter(a=>a.petId!==id);save();renderAll();toast("Mascota eliminada")};
$("addClientBtn").onclick=()=>{$("clientForm").reset();$("clientDialog").showModal()};
$("clientForm").onsubmit=e=>{e.preventDefault();state.data.clients.push({id:uid(),name:$("clientName").value.trim(),phone:$("clientPhone").value.trim(),email:$("clientEmail").value.trim(),address:$("clientAddress").value.trim(),notes:$("clientNotes").value.trim(),createdAt:new Date().toISOString()});save();$("clientDialog").close();renderAll();toast("Cliente guardado")};
window.deleteClient=id=>{if(!confirm("¿Eliminar este cliente?"))return;state.data.clients=state.data.clients.filter(c=>c.id!==id);save();renderAll();toast("Cliente eliminado")};
function fillPetSelect(id){$(id).innerHTML='<option value="">Selecciona una mascota</option>'+state.data.pets.map(p=>`<option value="${p.id}">${esc(p.name)} — ${esc(p.owner)}</option>`).join("")}
$("addAppointmentBtn").onclick=()=>{fillPetSelect("appointmentPet");$("appointmentForm").reset();fillPetSelect("appointmentPet");$("appointmentDialog").showModal()};
$("appointmentForm").onsubmit=e=>{e.preventDefault();state.data.appointments.push({id:uid(),petId:$("appointmentPet").value,date:$("appointmentDate").value,service:$("appointmentService").value.trim(),price:Number($("appointmentPrice").value||0),notes:$("appointmentNotes").value.trim()});save();$("appointmentDialog").close();renderAll();toast("Cita guardada")};
window.deleteAppointment=id=>{state.data.appointments=state.data.appointments.filter(a=>a.id!==id);save();renderAll();toast("Cita eliminada")};
$("addPaymentBtn").onclick=()=>{fillPetSelect("paymentPet");$("paymentForm").reset();$("paymentDate").value=new Date().toISOString().slice(0,10);fillPetSelect("paymentPet");$("paymentDialog").showModal()};
$("paymentForm").onsubmit=e=>{e.preventDefault();state.data.payments.push({id:uid(),petId:$("paymentPet").value,amount:Number($("paymentAmount").value||0),method:$("paymentMethod").value,date:$("paymentDate").value,notes:$("paymentNotes").value.trim()});save();$("paymentDialog").close();renderAll();toast("Pago registrado")};
window.deletePayment=id=>{state.data.payments=state.data.payments.filter(p=>p.id!==id);save();renderAll();toast("Pago eliminado")};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
function whatsapp(id){const p=state.data.pets.find(x=>x.id===id);if(!p?.phone)return toast("Esta mascota no tiene teléfono");const date=p.nextVisit?new Date(p.nextVisit+"T12:00:00").toLocaleDateString("es-EC"):null;openWhatsAppNumber(p.phone,`Hola ${p.owner||""} 🐾 Te escribimos de ELIT PET GROOMING. ${p.name} tiene ${date?`su próxima visita el ${date}`:"una cita pendiente"}. ¡Gracias por confiar en nosotros! ✂️🐶`)}
function openWhatsAppNumber(phone,msg){const clean=String(phone).replace(/\D/g,"");window.open(`https://wa.me/${clean}?text=${encodeURIComponent(msg)}`,"_blank")}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
let deferredPrompt;$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("installBtn").classList.add("hidden")}};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("installBtn").classList.remove("hidden")});
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
loadSession();
